version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - .env
#    volumes:
#      - ./.env:/app/.env
#      - ./target/gpt-telegrambot-0.0.1-SNAPSHOT.jar:/app/gptbot001.jar
    depends_on:
      - postgres

  postgres:
    image: postgres:14.12
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5430:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: