version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:14.12
#    restart: always
#    environment:
#      POSTGRES_DB: ${DATABASE_NAME}
#      POSTGRES_USER: ${DATABASE_USERNAME}
#      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5430:5432"
    env_file:
      - ./env/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2
#    restart: always
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    ports:
      - "6380:6379"
    env_file:
      - ./env/.env
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
